affinityCookieTtlSec: 0
backends:
- balancingMode: RATE
  capacityScaler: 1.0
  group: https://www.googleapis.com/compute/v1/projects/[PROJECT_ID]/zones/[ZONE]/networkEndpointGroups/[NEG_NAME_EDGE]
  maxRatePerEndpoint: 5.0
connectionDraining:
  drainingTimeoutSec: 0
description: ''
enableCDN: false
healthChecks:
- https://www.googleapis.com/compute/v1/projects/[PROJECT_ID]/global/healthChecks/edge-proxy-hcheck
kind: compute#backendService
loadBalancingScheme: EXTERNAL
name: edge-proxy-backend
port: 80
portName: http
protocol: HTTP
selfLink: https://www.googleapis.com/compute/v1/projects/[PROJECT_ID]/global/backendServices/edge-proxy-backend
sessionAffinity: NONE
timeoutSec: 30
